version: 2.1

parameters:
  image-type:
    type: string
    default: "ubuntu-2204:current"

executors:
  machine-ubuntu:
    machine:
      image: << parameters.image-type >>
    working_directory: ~/project

jobs:
  setup-ubuntu:
    description: >
      Creates directories and files using specified Ubuntu machine images.
    executor:
      name: machine-ubuntu
      image-type: << parameters.image-type >>
    steps:
      - checkout

      - run:
          name: Display Ubuntu Version
          command: lsb_release -a || cat /etc/os-release

      - run:
          name: Create Directory
          command: |
            mkdir -p ~/project_directory
            echo "Directory ~/project_directory created."

      - run:
          name: Create File
          command: |
            touch ~/project_directory/sample_file.txt
            echo "Sample file created at ~/project_directory/sample_file.txt"

      - run:
          name: List Directory Contents
          command: |
            ls -la ~/project_directory
            echo "Contents of ~/project_directory listed."

workflows:
  setup-workflow:
    jobs:
      - setup-ubuntu:
          matrix:
            image-type:
              - "ubuntu-2204:current"  # Ubuntu 22.04
              - "ubuntu-2004:current"  # Ubuntu 20.04
              - "ubuntu-2404:current"  # Ubuntu 24.04 (Ensure this image exists)
