version: 2.1


jobs:
  setup-ubuntu:
    parameters:
      image-type:
        type: string
        default: "ubuntu-2204:current"
    description: >
      Creates directories and files using specified Ubuntu machine images.
    machine:
      image: << parameters.image-type >>
    working_directory: ~/project
    steps:
      - checkout

      - run:
          name: Display Ubuntu Version
          command: lsb_release -a || cat /etc/os-release

      - run:
          name: Create Directory
          command: |
            mkdir -p ~/project_directory
            echo "Directory ~/project_directory created."

      - run:
          name: Create File
          command: |
            touch ~/project_directory/sample_file.txt
            echo "Sample file created at ~/project_directory/sample_file.txt"

      - run:
          name: List Directory Contents
          command: |
            ls -la ~/project_directory
            echo "Contents of ~/project_directory listed."
      - run:
          name: codacy
          command: |
            # Create the directory if it doesn't exist
            mkdir -p tmp
            
            # Create a sample XML report file
            cat <<"EOF" > tmp/test.xml
            <?xml version="1.0" encoding="UTF-8"?>
            <coverage>
              <file path="samplefile.py">
                <line number="1" hits="1"/>
                <line number="2" hits="0"/>
                <line number="3" hits="1"/>
              </file>
            </coverage>
            EOF
            
            # Upload the report to Codacy
            bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r tmp/test.xml


workflows:
  setup-workflow:
    jobs:
      - setup-ubuntu:
          matrix:
            parameters:
              image-type:
                - "ubuntu-2204:current"  # Ubuntu 22.04
                - "ubuntu-2004:current"  # Ubuntu 20.04
                - "ubuntu-2404:current"  # Ubuntu 24.04 (Ensure this image exists)
